import pytest
from hypothesis import given
from hypothesis import strategies as st

from pmrp.schemas.enums import Environment, HealthStatus
from pmrp.schemas.serialization import canonical_json, canonical_sha256
from pmrp.schemas.system import ServiceHealth

pytestmark = pytest.mark.property

_TRADING_IMPACTS = st.sampled_from(
    ("none", "strategy_only", "exchange_only", "account_only", "global")
)
_DEPENDENCY_NAMES = st.lists(
    st.from_regex(r"dep_[a-z0-9]{1,8}", fullmatch=True),
    min_size=0,
    max_size=5,
    unique=True,
)


def _service_payload(
    *,
    environment: Environment,
    status: HealthStatus,
    trading_impact: str,
    dependency_names: list[str],
) -> dict[str, object]:
    return {
        "service": "pmrp-api",
        "component": "operator-api",
        "environment": environment,
        "status": status,
        "since": "2026-07-28T19:00:00Z",
        "summary": "Service health generated by property test.",
        "last_success_at": "2026-07-28T19:14:00Z",
        "last_error_at": None,
        "dependencies": tuple(
            {
                "dependency": dependency_name,
                "status": HealthStatus.HEALTHY,
                "message": "Healthy.",
                "checked_at": "2026-07-28T19:15:00Z",
            }
            for dependency_name in dependency_names
        ),
        "trading_impact": trading_impact,
        "ready": True,
        "alive": True,
    }


@given(
    environment=st.sampled_from(tuple(Environment)),
    status=st.sampled_from(tuple(HealthStatus)),
    trading_impact=_TRADING_IMPACTS,
    dependency_names=_DEPENDENCY_NAMES,
)
def test_service_health_accepts_generated_enum_and_dependency_combinations(
    environment: Environment,
    status: HealthStatus,
    trading_impact: str,
    dependency_names: list[str],
) -> None:
    health = ServiceHealth.model_validate(
        _service_payload(
            environment=environment,
            status=status,
            trading_impact=trading_impact,
            dependency_names=dependency_names,
        )
    )

    assert health.environment is environment
    assert health.status is status
    assert health.trading_impact == trading_impact
    assert tuple(dependency.dependency for dependency in health.dependencies) == tuple(
        dependency_names
    )
    assert canonical_sha256(health) == canonical_sha256(
        ServiceHealth.model_validate_json(canonical_json(health))
    )


@given(dependency_names=_DEPENDENCY_NAMES)
def test_service_health_hash_is_stable_across_json_round_trips(
    dependency_names: list[str],
) -> None:
    health = ServiceHealth.model_validate(
        _service_payload(
            environment=Environment.TEST,
            status=HealthStatus.DEGRADED,
            trading_impact="none",
            dependency_names=dependency_names,
        )
    )

    canonical = canonical_json(health)

    assert canonical_sha256(health) == canonical_sha256(
        ServiceHealth.model_validate_json(canonical)
    )
