import pytest
from hypothesis import given
from hypothesis import strategies as st

from pmrp.schemas.enums import Environment, HealthStatus
from pmrp.schemas.serialization import canonical_json, canonical_sha256
from pmrp.schemas.system import AdapterHealth, RateLimitStatus, ServiceHealth

pytestmark = pytest.mark.property

_TRADING_IMPACTS = st.sampled_from(
    ("none", "strategy_only", "exchange_only", "account_only", "global")
)
_DEPENDENCY_NAMES = st.lists(
    st.from_regex(r"dep_[a-z0-9]{1,8}", fullmatch=True),
    min_size=0,
    max_size=5,
    unique=True,
)
_WINDOW_NAMES = st.lists(
    st.from_regex(r"window_[a-z0-9]{1,8}", fullmatch=True),
    min_size=0,
    max_size=5,
)


def _service_payload(
    *,
    environment: Environment,
    status: HealthStatus,
    trading_impact: str,
    dependency_names: list[str],
) -> dict[str, object]:
    return {
        "service": "pmrp-api",
        "component": "operator-api",
        "environment": environment,
        "status": status,
        "since": "2026-07-28T19:00:00Z",
        "summary": "Service health generated by property test.",
        "last_success_at": "2026-07-28T19:14:00Z",
        "last_error_at": None,
        "dependencies": tuple(
            {
                "dependency": dependency_name,
                "status": HealthStatus.HEALTHY,
                "message": "Healthy.",
                "checked_at": "2026-07-28T19:15:00Z",
            }
            for dependency_name in dependency_names
        ),
        "trading_impact": trading_impact,
        "ready": True,
        "alive": True,
    }


def _adapter_payload(
    *,
    environment: Environment,
    status: HealthStatus,
    connected: bool,
    authenticated: bool,
    subscriptions_active: bool,
    market_data_fresh: bool,
    trading_gate_open: bool,
    reconnect_attempts: int,
) -> dict[str, object]:
    return {
        "exchange": "kalshi",
        "environment": environment,
        "status": status,
        "connected": connected,
        "authenticated": authenticated,
        "subscriptions_active": subscriptions_active,
        "last_message_at": "2026-07-28T19:15:00Z",
        "last_heartbeat_at": "2026-07-28T19:14:59Z",
        "last_reconciliation_at": None,
        "market_data_fresh": market_data_fresh,
        "trading_gate_open": trading_gate_open,
        "reconnect_attempts": reconnect_attempts,
        "message": "Generated by property test.",
    }


def _rate_limit_status_payload(*, window_names: list[str], remaining: int) -> dict[str, object]:
    return {
        "exchange": "kalshi",
        "measured_at": "2026-07-28T19:15:00Z",
        "windows": tuple(
            {
                "name": window_name,
                "limit": remaining + 1,
                "remaining": remaining,
                "resets_at": "2026-07-28T19:16:00Z",
                "window_seconds": 60,
            }
            for window_name in window_names
        ),
    }


@given(
    environment=st.sampled_from(tuple(Environment)),
    status=st.sampled_from(tuple(HealthStatus)),
    trading_impact=_TRADING_IMPACTS,
    dependency_names=_DEPENDENCY_NAMES,
)
def test_service_health_accepts_generated_enum_and_dependency_combinations(
    environment: Environment,
    status: HealthStatus,
    trading_impact: str,
    dependency_names: list[str],
) -> None:
    health = ServiceHealth.model_validate(
        _service_payload(
            environment=environment,
            status=status,
            trading_impact=trading_impact,
            dependency_names=dependency_names,
        )
    )

    assert health.environment is environment
    assert health.status is status
    assert health.trading_impact == trading_impact
    assert tuple(dependency.dependency for dependency in health.dependencies) == tuple(
        dependency_names
    )
    assert canonical_sha256(health) == canonical_sha256(
        ServiceHealth.model_validate_json(canonical_json(health))
    )


@given(dependency_names=_DEPENDENCY_NAMES)
def test_service_health_hash_is_stable_across_json_round_trips(
    dependency_names: list[str],
) -> None:
    health = ServiceHealth.model_validate(
        _service_payload(
            environment=Environment.TEST,
            status=HealthStatus.DEGRADED,
            trading_impact="none",
            dependency_names=dependency_names,
        )
    )

    canonical = canonical_json(health)

    assert canonical_sha256(health) == canonical_sha256(
        ServiceHealth.model_validate_json(canonical)
    )


@given(
    environment=st.sampled_from(tuple(Environment)),
    status=st.sampled_from(tuple(HealthStatus)),
    connected=st.booleans(),
    authenticated=st.booleans(),
    subscriptions_active=st.booleans(),
    market_data_fresh=st.booleans(),
    trading_gate_open=st.booleans(),
    reconnect_attempts=st.integers(min_value=0, max_value=100),
)
def test_adapter_health_accepts_generated_state_combinations_and_hash_is_stable(
    environment: Environment,
    status: HealthStatus,
    connected: bool,
    authenticated: bool,
    subscriptions_active: bool,
    market_data_fresh: bool,
    trading_gate_open: bool,
    reconnect_attempts: int,
) -> None:
    health = AdapterHealth.model_validate(
        _adapter_payload(
            environment=environment,
            status=status,
            connected=connected,
            authenticated=authenticated,
            subscriptions_active=subscriptions_active,
            market_data_fresh=market_data_fresh,
            trading_gate_open=trading_gate_open,
            reconnect_attempts=reconnect_attempts,
        )
    )

    canonical = canonical_json(health)

    assert health.reconnect_attempts == reconnect_attempts
    assert canonical_sha256(health) == canonical_sha256(
        AdapterHealth.model_validate_json(canonical)
    )


@given(
    window_names=_WINDOW_NAMES,
    remaining=st.integers(min_value=0, max_value=1000),
)
def test_rate_limit_status_accepts_generated_windows_and_hash_is_stable(
    window_names: list[str],
    remaining: int,
) -> None:
    status = RateLimitStatus.model_validate(
        _rate_limit_status_payload(window_names=window_names, remaining=remaining)
    )
    canonical = canonical_json(status)

    assert tuple(window.name for window in status.windows) == tuple(window_names)
    assert canonical_sha256(status) == canonical_sha256(
        RateLimitStatus.model_validate_json(canonical)
    )
