"""Strategy interfaces and context primitives."""

from pmrp.strategies.baseline import (
    MIDPOINT_OBSERVER_CONFIGURATION_SCHEMA_VERSION,
    MIDPOINT_OBSERVER_STRATEGY_TYPE,
    MIDPOINT_OBSERVER_STRATEGY_VERSION,
    THRESHOLD_SIGNAL_CONFIGURATION_SCHEMA_VERSION,
    THRESHOLD_SIGNAL_STRATEGY_TYPE,
    THRESHOLD_SIGNAL_STRATEGY_VERSION,
    MidpointObservation,
    MidpointObserverConfiguration,
    MidpointObserverFactory,
    MidpointObserverStrategy,
    ThresholdSignalConfiguration,
    ThresholdSignalDecision,
    ThresholdSignalFactory,
    ThresholdSignalStrategy,
)
from pmrp.strategies.context import (
    APPROVED_STRATEGY_CONTEXT_SERVICES,
    FORBIDDEN_STRATEGY_CONTEXT_SERVICES,
    StrategyContext,
    StrategyLogger,
    StrategyMetrics,
    StrategyOrderIntentPublisher,
    StrategySignalPublisher,
)
from pmrp.strategies.errors import (
    StrategyContextError,
    StrategyEmissionError,
    StrategyError,
    StrategyLifecycleError,
    StrategyProtocolError,
    StrategyRegistryError,
    StrategyRestartPolicyError,
    StrategyRuntimeError,
    StrategyStateStoreError,
)
from pmrp.strategies.health import StrategyRuntimeHealth
from pmrp.strategies.lifecycle import (
    ALLOWED_STRATEGY_STATE_TRANSITIONS,
    TERMINAL_STRATEGY_STATES,
    transition_strategy_state,
    validate_strategy_state_transition,
)
from pmrp.strategies.protocol import Strategy, StrategyFactory
from pmrp.strategies.registry import (
    StrategyConfigurationModel,
    StrategyRegistry,
    StrategyTypeRegistration,
    UnknownStrategyTypeError,
)
from pmrp.strategies.restart import (
    BoundedRestartPolicy,
    NeverRestartPolicy,
    StrategyRestartDecision,
    StrategyRestartFailure,
    StrategyRestartFailureKind,
    StrategyRestartPolicy,
)
from pmrp.strategies.runtime import (
    StrategyLifecycleEvent,
    StrategyLifecycleEventPublisher,
    StrategyRuntime,
)
from pmrp.strategies.state_store import (
    InMemoryStrategyStateStore,
    StrategyStateCheckpoint,
    StrategyStateStore,
    thaw_checkpoint_state,
)

__all__ = [
    "ALLOWED_STRATEGY_STATE_TRANSITIONS",
    "APPROVED_STRATEGY_CONTEXT_SERVICES",
    "FORBIDDEN_STRATEGY_CONTEXT_SERVICES",
    "MIDPOINT_OBSERVER_CONFIGURATION_SCHEMA_VERSION",
    "MIDPOINT_OBSERVER_STRATEGY_TYPE",
    "MIDPOINT_OBSERVER_STRATEGY_VERSION",
    "TERMINAL_STRATEGY_STATES",
    "THRESHOLD_SIGNAL_CONFIGURATION_SCHEMA_VERSION",
    "THRESHOLD_SIGNAL_STRATEGY_TYPE",
    "THRESHOLD_SIGNAL_STRATEGY_VERSION",
    "BoundedRestartPolicy",
    "InMemoryStrategyStateStore",
    "MidpointObservation",
    "MidpointObserverConfiguration",
    "MidpointObserverFactory",
    "MidpointObserverStrategy",
    "NeverRestartPolicy",
    "Strategy",
    "StrategyConfigurationModel",
    "StrategyContext",
    "StrategyContextError",
    "StrategyEmissionError",
    "StrategyError",
    "StrategyFactory",
    "StrategyLifecycleError",
    "StrategyLifecycleEvent",
    "StrategyLifecycleEventPublisher",
    "StrategyLogger",
    "StrategyMetrics",
    "StrategyOrderIntentPublisher",
    "StrategyProtocolError",
    "StrategyRegistry",
    "StrategyRegistryError",
    "StrategyRestartDecision",
    "StrategyRestartFailure",
    "StrategyRestartFailureKind",
    "StrategyRestartPolicy",
    "StrategyRestartPolicyError",
    "StrategyRuntime",
    "StrategyRuntimeError",
    "StrategyRuntimeHealth",
    "StrategySignalPublisher",
    "StrategyStateCheckpoint",
    "StrategyStateStore",
    "StrategyStateStoreError",
    "StrategyTypeRegistration",
    "ThresholdSignalConfiguration",
    "ThresholdSignalDecision",
    "ThresholdSignalFactory",
    "ThresholdSignalStrategy",
    "UnknownStrategyTypeError",
    "thaw_checkpoint_state",
    "transition_strategy_state",
    "validate_strategy_state_transition",
]
