"""Exchange adapter interfaces and shared adapter contracts."""

from pmrp.adapters.base import (
    AdapterAmbiguousOrderSubmissionError,
    AdapterAuthenticationError,
    AdapterCapabilities,
    AdapterCapabilityError,
    AdapterEndpointCategory,
    AdapterError,
    AdapterProtocolError,
    AdapterRateLimitDecision,
    AdapterRateLimitError,
    AdapterRateLimitRule,
    AdapterSequenceGapError,
    AdapterTimeoutError,
    AdapterTransportError,
    ExchangeAdapter,
    MarketDataChannel,
    MarketListRequest,
    MarketSubscription,
    RawBalance,
    RawExchangeEvent,
    RawFill,
    RawMarket,
    RawOpenOrder,
    RawPosition,
    evaluate_rate_limit,
)
from pmrp.adapters.fixture import FixtureAdapter, FixtureAdapterFailureMode

__all__ = [
    "AdapterAmbiguousOrderSubmissionError",
    "AdapterAuthenticationError",
    "AdapterCapabilities",
    "AdapterCapabilityError",
    "AdapterEndpointCategory",
    "AdapterError",
    "AdapterProtocolError",
    "AdapterRateLimitDecision",
    "AdapterRateLimitError",
    "AdapterRateLimitRule",
    "AdapterSequenceGapError",
    "AdapterTimeoutError",
    "AdapterTransportError",
    "ExchangeAdapter",
    "FixtureAdapter",
    "FixtureAdapterFailureMode",
    "MarketDataChannel",
    "MarketListRequest",
    "MarketSubscription",
    "RawBalance",
    "RawExchangeEvent",
    "RawFill",
    "RawMarket",
    "RawOpenOrder",
    "RawPosition",
    "evaluate_rate_limit",
]
